### ISSUE TITLE
Derive Serialize and Deserialize for public-facing structs

### ISSUE THREAD

**Issue by bonsairobo** [whatisaphone/rlbot-rust#6]
It would be useful to be able to use Serialize and Deserialize for the MatchSettings type (among others).

**Comment by whatisaphone** [comment]
Can you share a little bit more about your envisioned use case?

**Comment by whatisaphone** [comment]
That's a reasonable use-case, but there are some difficulties to implementing this:

1. RLBot changes their data format occasionally, and every time they do it would break all the data from previous versions (including your config files).

2. The FFI uses some inconvenient types, for example the [player name](https://docs.rs/rlbot/0.1.2/rlbot/ffi/struct.PlayerConfiguration.html#structfield.Name) is:

   ```rust
   Name: [u16; 32]
   ```

   There's no way that will serialize nicely in yaml.

3. The ffi bindings are generated with bindgen, and it has no way to add your own derives (that I can see). Doing it all by hand would be quite tedious.

So right now I'm leaning towards not doing this, unless you have some ideas to overcome these issues. Maybe instead of using yaml or json for your config files, you could use rust instead 😄

**Comment by bonsairobo** [comment]
I don't currently need this feature so I'm fine with waiting a bit for the API to stabilize.
